name: Photography Art Prints
favicon: null
layout_spectrum: 0.8449530920479447
typography_spectrum: 0.6512154960073531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8799632340669632
  lightness: 0.6743230661377311
  saturation: 0.02904863189905882
  rhythmicContrast: 0.7898218675982207
purpose: []
