name: Photography Art Prints
favicon: null
layout_spectrum: 0.50162
typography_spectrum: 0.24455
title: Photography Art Prints by John Shepherd Photography.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#898989'
    - '#a4a4a4'
    - '#c2c2c2'
    - '#575757'
    - '#212121'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
