name: Photography Art Prints
favicon: null
layout_spectrum: 0.50162
typography_spectrum: 0.24455
title: Photography Art Prints by John Shepherd Photography.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8799632340669632
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
